# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'whatsMyFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for whatsMyFood

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
  ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core', '~> 6.3.0'

  pod 'Firebase/Auth', '~> 6.3.0'

  pod 'Firebase/Storage', '~> 6.3.0'

  pod 'Fabric', '~> 1.10.2'
  
  pod 'Crashlytics', '~> 3.13.2'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'GoogleSignIn', '~> 4.4.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
  end
end
